In [2]:
from sklearn.neighbors import KDTree
import numpy as np

data = np.fromfile('./test_data/2024-05-27-11-39-07_Velodyne-VLS-128-Data_out.bin')
data =data.reshape(-1,4)
print(data)
print(data.shape)

[[6.78818730e+05 1.51456634e+06 7.64000000e+00 1.50000000e+01]
 [6.78818700e+05 1.51456633e+06 7.58000000e+00 3.40000000e+01]
 [6.78818680e+05 1.51456631e+06 7.54000000e+00 1.30000000e+01]
 ...
 [6.78814830e+05 1.51457840e+06 2.80000000e-01 7.00000000e+00]
 [6.78813380e+05 1.51457999e+06 4.20000000e-01 1.20000000e+01]
 [6.78817050e+05 1.51457930e+06 6.40000000e-01 1.70000000e+01]]
(6000000, 4)


In [4]:
from sklearn.neighbors import KDTree
import numpy as np

tree =np.load('./test_data_prepared_0.06/KDTree/2024-05-27-11-39-07_Velodyne-VLS-128-Data_out.pkl')
points = np.array(tree.data, copy=False)

In [7]:
print(points)
print(points.shape)


[[ 2.02441176e+34  2.89700508e+00  0.00000000e+00]
 [ 2.22011771e+34  2.84684348e+00  0.00000000e+00]
 [ 2.74902264e+34  2.78745079e+00  0.00000000e+00]
 [ 2.31302832e+34  2.73064089e+00  0.00000000e+00]
 [ 2.29426363e+34  2.66723657e+00  0.00000000e+00]
 [ 8.91309062e+04  1.03497100e+00  0.00000000e+00]
 [ 2.39373681e+34 -2.30507445e+00  0.00000000e+00]
 [-3.21872146e+26  1.23999655e+00  0.00000000e+00]
 [ 2.35602272e+34 -2.19925761e+00  0.00000000e+00]
 [-1.62606444e+26  1.34533119e+00  0.00000000e+00]
 [-3.08039376e+31 -1.93671870e+00  0.00000000e+00]
 [-5.26323009e+25  1.59006226e+00  0.00000000e+00]
 [ 2.26673780e+22 -2.02135420e+00  0.00000000e+00]
 [ 8.58061924e+28  1.53222013e+00  0.00000000e+00]
 [-7.59982971e+13 -1.91499996e+00  0.00000000e+00]
 [ 3.81522533e+22  1.65524721e+00  0.00000000e+00]
 [ 2.53500286e+34 -2.07401061e+00  0.00000000e+00]
 [-1.09634433e+26  1.47023499e+00  0.00000000e+00]
 [ 8.73380808e+28 -1.53229725e+00  0.00000000e+00]
 [            inf  2.01146269e+

In [8]:
from sklearn.neighbors import KDTree
import numpy as np

tree_2 =np.load('./test_data_prepared_0.06/KDTree/2024-05-27-11-39-07_Velodyne-VLS-128-Data_out.pkl')
points_2 = np.array(tree.data, copy=False)
print(points)
print(points.shape)

[[ 2.02441176e+34  2.89700508e+00  0.00000000e+00]
 [ 2.22011771e+34  2.84684348e+00  0.00000000e+00]
 [ 2.74902264e+34  2.78745079e+00  0.00000000e+00]
 [ 2.31302832e+34  2.73064089e+00  0.00000000e+00]
 [ 2.29426363e+34  2.66723657e+00  0.00000000e+00]
 [ 8.91309062e+04  1.03497100e+00  0.00000000e+00]
 [ 2.39373681e+34 -2.30507445e+00  0.00000000e+00]
 [-3.21872146e+26  1.23999655e+00  0.00000000e+00]
 [ 2.35602272e+34 -2.19925761e+00  0.00000000e+00]
 [-1.62606444e+26  1.34533119e+00  0.00000000e+00]
 [-3.08039376e+31 -1.93671870e+00  0.00000000e+00]
 [-5.26323009e+25  1.59006226e+00  0.00000000e+00]
 [ 2.26673780e+22 -2.02135420e+00  0.00000000e+00]
 [ 8.58061924e+28  1.53222013e+00  0.00000000e+00]
 [-7.59982971e+13 -1.91499996e+00  0.00000000e+00]
 [ 3.81522533e+22  1.65524721e+00  0.00000000e+00]
 [ 2.53500286e+34 -2.07401061e+00  0.00000000e+00]
 [-1.09634433e+26  1.47023499e+00  0.00000000e+00]
 [ 8.73380808e+28 -1.53229725e+00  0.00000000e+00]
 [            inf  2.01146269e+

## Load predicted data

In [2]:
import numpy as np
import os

# Path to predictions directory
predictions_dir = './test/sequence/predictions/'
# data_dir


# List all .label files in the directory
label_files = [f for f in os.listdir(predictions_dir) if f.endswith('.label')]

# Initialize an empty set for unique values
unique_values = set()

# Read each file and extract unique values
for file in label_files:
    file_path = os.path.join(predictions_dir, file)
    predicted_file = np.fromfile(file_path, dtype=np.uint32)
    print(file,predicted_file.shape)
    unique_values.update(np.unique(predicted_file))  # Add unique values to the set

# Convert set to sorted numpy array for better readability
unique_values = np.array(sorted(unique_values))

print(unique_values)


combined_part_1.label (22500000,)
combined_part_2.label (22500000,)
combined_part_3.label (22500000,)
combined_part_4.label (22500000,)
combined_part_5.label (22500000,)
combined_part_6.label (22500000,)
combined_part_7.label (22500000,)
combined_part_8.label (22500000,)
[10]


In [ ]:
import os
import numpy as np

def load_pc_kitti(pc_path):
    scan = np.fromfile(pc_path, dtype=np.float32)
    scan = scan.reshape((-1, 4))
    points = scan[:, 0:3]  # get xyz
    return points



datadir = '../data_converter/semantic_kitti/dataset/sequences/14/velodyne/000000.bin'
prepared = 'semantic_prepared/velodyne/000000.npy'
labeldir = "test/sequences/predictions/000000.label"
pc = load_pc_kitti(datadir)
pc_prepared = np.load(prepared)
label = np.fromfile(labeldir,dtype=np.uint32)

# print shape
print("Original PC shape:", pc.shape)
print("Prepared PC shape:", pc_prepared.shape)
print("Label shape:", label.shape)



print(pc[:4])
print(pc_prepared[:4])
print(label)



Original PC shape: (120066, 3)
Prepared PC shape: (86822, 3)
Label shape: (120066,)
[[5.5064964e+01 2.6010770e-02 2.0709999e+00]
 [5.5056728e+01 1.9808201e-01 2.0709977e+00]
 [5.5490494e+01 3.7515527e-01 2.0859950e+00]
 [5.9143257e+01 5.8724225e-01 2.2089920e+00]]
[[ 3.7714028 -1.3904846 -1.7467372]
 [ 3.6794991 -1.3614844 -1.7017289]
 [ 3.7266767 -1.4465044 -1.7357374]
 [ 3.7377315 -1.4540055 -1.7417389]]
[50 50 50 ... 48 48 48]


In [ ]:
import laspy
import numpy as np
import open3d as o3d

# Load LAS file
def load_las(las_file):
    las = laspy.read(las_file)
    xyz = np.vstack([las.x, las.y, las.z]).transpose()  # Extract XYZ coordinates
    return xyz

# Convert LAS to PLY
def convert_las_to_ply(las_file, ply_file):
    # Read LAS file
    points = load_las(las_file)
    
    # Create an Open3D point cloud object
    point_cloud = o3d.geometry.PointCloud()
    
    # Set the points (the xyz values)
    point_cloud.points = o3d.utility.Vector3dVector(points)
    
    # Optionally, add intensity or color to the point cloud (if needed)
    # point_cloud.colors = o3d.utility.Vector3dVector(colors)  # Colors should be normalized to [0, 1]
    
    # Write to PLY
    o3d.io.write_point_cloud(ply_file, point_cloud)
    print(f"PLY file saved at {ply_file}")

# Example usage
las_file = './output.las'
ply_file = 'output.ply'
convert_las_to_ply(las_file, ply_file)


SyntaxError: invalid syntax (vlrlist.py, line 30)